### PR TITLE
Fix on requests page to show correct type and on click navigation to review transaction

### PR DESCRIPTION
**Pull request by hcho112**
1. Fix on showing correct `type` on both pending and completed pages:
Pending Page:
image

Completed Page:
image

(I have removed icon that was on the left side of the word `Outgoing transfer`. Now that we are showing all different types, its not eligible to show just one icon that represents outgoing. I'm happy to update UI to include icons if I can get access to list of possible actions and recommended icons) 

2. Fix on click navigation on `completed page` to show transaction page in explorer instead of showing account page:
image
image

(I wasn't able to update on `pending page` because I wasn't able to retrieve/reference the correct transaction hash. If I can get some help to reference it correctly, I will also make changes on pending page)

### CODE REVIEW

**Review by judith-Near — DISMISSED** [review]
we don't need the yarn.lock change so if you could revert that, that'd be great! otherwise, great work, lgtm!

another thing, we can address in this PR or follow up PR, the types should be more human readable, ie Set Number Confirmations, not SetNumConfirmations. @heycorwin what icons in [material ui](https://v4.mui.com/components/material-icons/) should be used for the following actions: 

set number of confirmations (suggestion: Settings in material ui icons)
add member (suggestion: GroupAdd)
remove member (suggestion: Group)
transfer tokens (nft or ft) (suggestion: CallMade)

**Comment by agileurbanite** [comment]
Can we make the type info more human readable?  So create a map for types to strings @hcho112 ?  I hate to pick on a nit like this but seems pretty simple imo to get this done with minimal effort

**Comment by hcho112** [comment]
@judith-Near @agileurbanite Thank you the the reviews. I will definitely make theses updates shortly

**Comment by hcho112** [comment]
Update:
1. Reverted change on yarn.lock file
2. Replaced the action type with more readable format with icons:
image

**Review by judith-Near — APPROVED** [review]

**Pull request merged**
